runtime: nodejs20
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

env_variables:
  MAIL_USERNAME: "info@simonainc.com"
  MAIL_PASSWORD: "yuloboxkdlzsifnz"

handlers:
- url: /app/.*
  script: auto

- url: /.*
  static_dir: static/