runtime: nodejs20
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.+)
  static_files: \1
  upload: .+

- url: /.*
  static_files: index.html
  upload: index.html
